# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b2d5ea5ddbaab057463bfe9c404586d5"
name = "Dashboard FEL"
handle = "dashboard-fel"
application_url = "https://concepts-cc-suspension-packages.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,read_customers,read_reports"

[auth]
redirect_urls = ["https://concepts-cc-suspension-packages.trycloudflare.com/auth/callback", "https://concepts-cc-suspension-packages.trycloudflare.com/auth/shopify/callback", "https://concepts-cc-suspension-packages.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
